version: '3.3'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0111@Ahmed
      MYSQL_DATABASE: alsham
      MYSQL_USER: ahmed
      MYSQL_PASSWORD: 0111@Ahmed
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    # networks:
    #   - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=0111@Ahmed
      - SERVER_NAME=164.92.200.16
      - PMA_ABSOLUTE_URI=http://164.92.200.16:8000/
    volumes:
      - phpmyadmin_data:/sessions
    ports:
      - "8000:8000"
    depends_on:
      - db
    # networks:
    #   - my-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  db_data:
  phpmyadmin_data:

# networks:
#   my-network:
