version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0111@Ahmed
      MYSQL_DATABASE: alsham
      MYSQL_USER: ahmed
      MYSQL_PASSWORD: 0111@Ahmed
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=ahmed
      - PMA_PASSWORD=0111@Ahmed
    ports:
      - "8080:80"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    # restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  db_data:
